# Generated by Django 5.2.5 on 2025-08-23 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantumBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(default='IBM', max_length=50)),
                ('is_simulator', models.BooleanField(default=True)),
                ('num_qubits', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('qiskit_code', models.TextField()),
                ('circuit_image', models.ImageField(blank=True, null=True, upload_to='circuit_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_jobs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantum_jobs', to=settings.AUTH_USER_MODEL)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.quantumbackend')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.JSONField(blank=True, null=True)),
                ('probabilities', models.JSONField(blank=True, null=True)),
                ('shots', models.IntegerField(default=1024)),
                ('calibration_data', models.JSONField(blank=True, null=True)),
                ('histogram_image', models.ImageField(blank=True, null=True, upload_to='result_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_results', to='jobs.job')),
            ],
        ),
    ]
