# Generated by Django 5.2.5 on 2025-08-23 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('jobs_submitted', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('jobs_failed', models.IntegerField(default=0)),
                ('jobs_running', models.IntegerField(default=0)),
                ('jobs_queued', models.IntegerField(default=0)),
                ('avg_waiting_time_ms', models.FloatField(default=0)),
                ('avg_execution_time_ms', models.FloatField(default=0)),
                ('total_execution_time_ms', models.BigIntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('queue_length', models.IntegerField(default=0)),
                ('avg_queue_wait_time_ms', models.FloatField(default=0)),
                ('cpu_usage_percent', models.FloatField(default=0)),
                ('memory_usage_percent', models.FloatField(default=0)),
                ('error_rate_percent', models.FloatField(default=0)),
                ('timeout_rate_percent', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackendUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jobs_count', models.IntegerField(default=0)),
                ('total_execution_time_ms', models.BigIntegerField(default=0)),
                ('avg_execution_time_ms', models.FloatField(default=0)),
                ('success_rate', models.FloatField(default=0)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.quantumbackend')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('backend', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('jobs_completed', 'Jobs Completed'), ('execution_time', 'Total Execution Time'), ('examples_run', 'Examples Completed'), ('collaboration', 'Most Collaborative')], max_length=20)),
                ('score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('user', 'leaderboard_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jobs_submitted', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('examples_run', models.IntegerField(default=0)),
                ('comments_made', models.IntegerField(default=0)),
                ('total_session_time_minutes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
